#!/bin/bash
case `lsb_release -cs` in
	helena)
		UBUVER="karmic" ;;
	isadora)
		UBUVER="lucid" ;;
	julia)
		UBUVER="maverick" ;;
	katya)
		UBUVER="natty" ;;
	lisa)
		UBUVER="oneiric" ;;
	maya)
		UBUVER="precise" ;;
esac

if [[ "$(lsb_release -rs)" > "11.04" || $UBUVER = "oneiric" || $UBUVER = "precise" ]]; then
	auth="pkexec"
else
	if [[ -e /usr/bin/kdesudo ]]; then
		auth="kdesudo -d --comment=\"Y PPA Manager requires admin privileges for this task\""
	elif [[ -e /usr/bin/gksu ]]; then 
		auth="gksu -S -m \"Y PPA Manager requires admin privileges for this task\""
	else
		echo "No authentication program found."
		exit 1
	fi
fi
case $1 in
	add)
		"$auth" y-ppa-cmd add;;
	advanced)
		"$auth" y-ppa-cmd advanced;;
	manage)
		"$auth" y-ppa-cmd manage;;
	search)
		"$auth" y-ppa-search;;
	settings)
		"$auth" y-ppa-cmd settings;;
	install)
		"$auth" y-ppa-cmd install;;
	*)
		y-ppa-indicator &
		"$auth" y-ppa-manager;;
esac
