#!/usr/bin/python

#Some bits of code thanks to Alex Simenduev <shamil.si@gmail.com> (via Indicator-PLaces)

import gtk
import appindicator
import os
import signal
import dbus



def item_run(w, yitem):
    if yitem == "_yppa" :
        os.system("y-pkexec")
    elif yitem == "_yppa_search":
        os.system("rm -f '/tmp/.yppa_username' '/tmp/.yppa_home' && y-pkexec search")
    elif yitem == "_yppa_add":
        os.system("rm -f '/tmp/.yppa_username' '/tmp/.yppa_home' && y-pkexec add")
    elif yitem == "_yppa_manage":
        os.system("rm -f '/tmp/.yppa_username' '/tmp/.yppa_home' && y-pkexec manage")
    elif yitem == "_yppa_install":
        os.system("y-pkexec install")
    elif yitem == "_yppa_adv":
        os.system("rm -f '/tmp/.yppa_username' '/tmp/.yppa_home' && y-pkexec advanced")
    elif yitem == "_yppa_set":
        os.system("rm -f '/tmp/.yppa_username' '/tmp/.yppa_home' && y-pkexec settings")
    elif yitem == "_yppa_quit":
	#todo: find a better way to exist main Y PPA Manager window, "killall yad" isn't exactly a good idea
        os.system("killall yad") 
	gtk.main_quit()


class IndicatorY:

    def __init__(self):
	if dbus.SessionBus().request_name('instance.y-ppa-indicator') != dbus.bus.REQUEST_NAME_REPLY_PRIMARY_OWNER:
	    print "application already running"
	    exit(0)
        self.ind = appindicator.Indicator("y-ppa-indicator", "y-ppa-indicator", appindicator.CATEGORY_APPLICATION_STATUS)
        self.ind.set_status(appindicator.STATUS_ACTIVE)
	hud_naming = True
	try:
        	self.ind.set_property ("title", ("Y PPA Manager"))
	except:
		hud_naming = False

        self.create_menu()

    def create_menu(self, widget = None, data = None):

        # Create menu
        menu = gtk.Menu()

        # List items
        item = gtk.MenuItem("Add PPA")
        item.connect("activate", item_run, "_yppa_add")
        menu.append(item)

        item = gtk.MenuItem("Search in all Launchpad PPAs")
        item.connect("activate", item_run, "_yppa_search")
        menu.append(item)

        item = gtk.MenuItem("Manage PPAs")
        item.connect("activate", item_run, "_yppa_manage")
        menu.append(item)

        item = gtk.MenuItem("Install packages")
        item.connect("activate", item_run, "_yppa_install")
        menu.append(item)

        item = gtk.MenuItem("Advanced")
        item.connect("activate", item_run, "_yppa_adv")
        menu.append(item)

        # Show separator
        item = gtk.SeparatorMenuItem()
        menu.append(item)

        # More items
        item = gtk.MenuItem("Settings")
        item.connect("activate", item_run, "_yppa_set")
        menu.append(item)

        item = gtk.MenuItem("Y PPA Manager")
        item.connect("activate", item_run, "_yppa")
        menu.append(item)

        # Quit menu item
        item = gtk.MenuItem("Quit")
        item.connect("activate", item_run, "_yppa_quit")
        menu.append(item)

        self.ind.set_menu(menu)
        menu.show_all()

if __name__ == "__main__":
    # Catch CTRL-C
    signal.signal(signal.SIGINT, lambda signal, frame: gtk.main_quit())

    # Run the indicator
    i = IndicatorY()
             
    # Main gtk loop
    gtk.main()
