#!/bin/bash
LANG=en_US.UTF-8
#echo "$$" > /tmp/y_pid
Y_RUN_INDICATOR_TRUE=`grep "indicator=enabled" /etc/y-ppa-manager.conf`

function Y_MAIN_DIALOG() {
Y_RUN=$(yad --icons --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --item-width="182" --read-dir="/usr/share/y-ppa-manager/desktopfiles" --width="435" --height="440" --title="Y PPA Manager" --text="\n  <b>Double click</b> an item to perform an action:" --button="Help:0" --button="Close:1")
ret=$?
if [[ $ret -eq 0 ]]; then
	Y_MAIN_DIALOG &
	y-ppa-cmd help &
else
	[[ `grep "indicator=enabled" /etc/y-ppa-manager.conf` ]] && killall y-ppa-indicator > /dev/null 2>&1
	rm -f "/tmp/.yppa_username" "/tmp/.yppa_home"
	exit 0
fi
}

[[ `grep "indicator=disabled" /etc/y-ppa-manager.conf` ]] && killall y-ppa-indicator > /dev/null 2>&1
Y_MAIN_DIALOG &
