#!/bin/bash
LANG=en_US.UTF-8
check_root() {
if [[ ! $(whoami) = "root" ]]; then
	exec sudo "$0" "$@"
fi
}

check_root "$@"

function CLEARTEMP () 
{
	rm /tmp/.temp_sourcesnames2.list /tmp/.temp_sources2.list /tmp/.non_disabled2.list /tmp/.temp_sourcesnames.list /tmp/.temp_sources.list /tmp/.non_disabled.list /tmp/+ppas* /tmp/.list_search_results /tmp/.Packages /tmp/.package_search_list_results /tmp/.package_search_list_results2 /tmp/.packagename /tmp/.packageversion /tmp/.packagename2 /tmp/.packageversion2 /tmp/.searched_ppa_names /tmp/.searched_ppas /tmp/.testinternet /tmp/.added_ppa /tmp/.dupes_to_remove /tmp/.dupes_show /tmp/.rmdups /tmp/.y_ppalist.list /tmp/add-apt-repository-help.tmp /tmp/.y_* > /dev/null 2>&1
}

ROOT_UID=0
#UBUVER=`lsb_release -cs`
#ON_USER=$(echo ~ | awk -F'/' '{ print $1 $2 $3 }' | sed 's/home//g')
ON_USER=$(who | awk '{print $1}' | sed '/^root$/d' | uniq)

function version { echo "$@" | awk -F. '{ printf("%d%03d\n", $1,$2); }'; }
RELEASE=$(lsb_release -r | cut -f2)

UBUVER="$(lsb_release -cs)"
case `lsb_release -cs` in
	helena)
		UBUVER="karmic" ;;
	isadora)
		UBUVER="lucid" ;;
	julia)
		UBUVER="maverick" ;;
	katya)
		UBUVER="natty" ;;
	lisa)
		UBUVER="oneiric" ;;
	maya)
		UBUVER="precise" ;;
	nadia)
		UBUVER="quantal" ;;
	olivia)
		UBUVER="raring" ;;
	petra)
		UBUVER="saucy" ;;
	qiana|rebecca|rafaela|rosa|freya)
		UBUVER="trusty" ;;
	luna)
		UBUVER="precise" ;;
	sarah|loki|serena|sonya|sylvia)
		UBUVER="xenial" ;;
	tara|juno|tessa|tina|tricia|hera)
		UBUVER="bionic" ;;
	odin|ulyana|ulyssa|uma)
		UBUVER="focal" ;;
esac

# Temporary work-around for Linux Mint 16 add-apt-repository
if [ `lsb_release -cs` = "petra" ]; then
	if ! grep -q "petra" /usr/share/python-apt/templates/LinuxMint.info 2>/dev/null; then
	echo "
Suite: petra
RepositoryType: deb
BaseURI: http://packages.linuxmint.com/
MatchURI: packages.linuxmint.com
MirrorsFile-amd64: /usr/share/python-apt/templates/LinuxMint.mirrors
MirrorsFile-i386: /usr/share/python-apt/templates/LinuxMint.mirrors
Description: Linux Mint 16 'Petra'
Component: main
CompDescription: Main packages
CompDescriptionLong: Main packages
Component: upstream
CompDescription: Upstream packages
CompDescriptionLong: Upstream packages
Component: import
CompDescription: Imported packages
CompDescriptionLong: Imported packages
Component: backport
CompDescription: Backports
CompDescriptionLong: Backported packages
Component: romeo
CompDescription: Unstable packages
CompDescriptionLong: Unstable packages" >> /usr/share/python-apt/templates/LinuxMint.info
	fi
fi
# Temporary work-around for Linux Mint 17 add-apt-repository
if [ `lsb_release -cs` = "qiana" ]; then
	if ! grep -q "qiana" /usr/share/python-apt/templates/LinuxMint.info 2>/dev/null; then
	echo "
Suite: qiana
RepositoryType: deb
BaseURI: http://packages.linuxmint.com/
MatchURI: packages.linuxmint.com
MirrorsFile-amd64: /usr/share/python-apt/templates/LinuxMint.mirrors
MirrorsFile-i386: /usr/share/python-apt/templates/LinuxMint.mirrors
Description: Linux Mint 17 'Qiana'
Component: main
CompDescription: Main packages
CompDescriptionLong: Main packages
Component: upstream
CompDescription: Upstream packages
CompDescriptionLong: Upstream packages
Component: import
CompDescription: Imported packages
CompDescriptionLong: Imported packages
Component: backport
CompDescription: Backports
CompDescriptionLong: Backported packages
Component: romeo
CompDescription: Unstable packages
CompDescriptionLong: Unstable packages" >> /usr/share/python-apt/templates/LinuxMint.info
	fi
fi

loggeduser=$(cat /tmp/.yppa_username)
homedir=$(cat /tmp/.yppa_home)
######policykit fix for KDE not setting XAUTHORITY
release="$(lsb_release -rs)"
if [[ "$release" > "11.04" || "$UBUVER" = "oneiric" || "$UBUVER" = "precise" || "$UBUVER" = "quantal" || "$UBUVER" = "raring" || "$UBUVER" = "saucy" || "$UBUVER" = "trusty" || "$UBUVER" = "utopic" || "$UBUVER" = "vivid" || "$UBUVER" = "wily" || "$UBUVER" = "xenial" || "$UBUVER" = "yakkety" || "$UBUVER" = "zesty" || "$UBUVER" = "artful" || "$UBUVER" = "bionic" || "$UBUVER" = "cosmic" || "$UBUVER" = "disco" || "$UBUVER" = "eoan" || "$UBUVER" = "focal" || "$UBUVER" = "groovy" || "$UBUVER" = "hirsute" || "$UBUVER" = "impish" ]]; then
	[[ -z "$XAUTHORITY" ]] && export XAUTHORITY="$homedir/.Xauthority"
fi
########

WMPID=$(ps -u $loggeduser | tail -n 1 | awk '{print $1}')
DBUS=$(egrep -z 'DBUS_SESSION_BUS_ADDRESS|DISPLAY' /proc/${WMPID}/environ | sed -r -e 's/(.)DBUS_/\1 DBUS_/' -e 's/(.)DISPLAY/\1 DISPLAY/')
########



#check if the user has an active internet connection
function testConnection() 
{
	testconnection=`wget --no-check-certificate --tries=3 --timeout=15 www.google.com -O /tmp/.testinternet &>/dev/null 2>&1`
	if [[ $? != 0 ]]; then
		echo  "You are not connected to the Internet. Please check your Internet connection and try again."
		yad --center --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --form --title="Internet connection error" --text="   You don't seem to be connected to the Internet.   \n   This function needs a working internet connection (and working wget)   " --button="gtk-ok:0"
		ppa_manager_run
	else
		echo Internet connection - ok
		rm /tmp/.testinternet  > /dev/null 2>&1
	fi
}

function checkAPT()
{
	sleep 1
	for lock in synaptic update-manager software-center apt-get "dpkg " aptitude
	do
		if ps -U root -u root u | grep "$lock" | grep -v grep > /dev/null;
			then 
				echo "Installation won't work. Please close $lock first then try again.";
				yad --center --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --form --title="Warning - Y PPA Manager" --text="\n\n  Selected action won't work.  \n\n  Please close / wait for <b>$lock</b> to finish and try again!   \n" --button="gtk-ok:0"
				exit
		fi
	done
}
     
function y_add_ppa ()
{
if [[ `lsb_release -cs` = "olivia" ]]; then
	/usr/lib/y-ppa-manager/add-apt-repository -y $1 &> /tmp/.added_ppa
	mintfix=$(echo "$1" | sed -e 's/ppa://g' -e 's/\//-/g')
	mv /etc/apt/sources.list.d/"$mintfix"-olivia.list /etc/apt/sources.list.d/"$mintfix"-raring.list
        sed -i 's/olivia/raring/g' /etc/apt/sources.list.d/"$mintfix"-raring.list
	update-ppa $1 > /dev/null 2>&1
elif [[ `lsb_release -cs` = "petra" ]]; then
	/usr/lib/y-ppa-manager/add-apt-repository -y $1 &> /tmp/.added_ppa
	mintfix=$(echo "$1" | sed -e 's/ppa://g' -e 's/\//-/g')
	mv /etc/apt/sources.list.d/"$mintfix"-petra.list /etc/apt/sources.list.d/"$mintfix"-saucy.list
        sed -i 's/petra/saucy/g' /etc/apt/sources.list.d/"$mintfix"-saucy.list
	update-ppa $1 > /dev/null 2>&1
elif [[ `lsb_release -cs` = "qiana" ]]; then
	/usr/lib/y-ppa-manager/add-apt-repository -y $1 &> /tmp/.added_ppa
	mintfix=$(echo "$1" | sed -e 's/ppa://g' -e 's/\//-/g')
	mv /etc/apt/sources.list.d/"$mintfix"-qiana.list /etc/apt/sources.list.d/"$mintfix"-trusty.list
        sed -i 's/qiana/trusty/g' /etc/apt/sources.list.d/"$mintfix"-trusty.list
	update-ppa $1 > /dev/null 2>&1
elif [[ `add-apt-repository --help 2>&1 | grep "\-y, --yes"` ]]; then
	add-apt-repository -y $1 &> /tmp/.added_ppa && update-ppa $1
else
	add-apt-repository $1 &> /tmp/.added_ppa && update-ppa $1
fi
#work-around for stupid add-apt-repository bug which adds non-existent ppa when using -y
ERRORREADINGPPA=$(grep "Error reading" /tmp/.added_ppa || grep "Cannot add" /tmp/.added_ppa)
if [[ "$ERRORREADINGPPA" ]]; then
	first=$(echo $1 | sed -e "s/ppa://g" | sed -e 's/[.+]/_/g' | cut -d '/' -f 1)
	second=$(echo $1 | sed -e "s/ppa://g" | sed -e 's/[.+]/_/g' | cut -d '/' -f 2)
	if [[ `lsb_release -cs` = "olivia" || `lsb_release -cs` = "petra" || `lsb_release -cs` = "qiana" || `add-apt-repository --help 2>&1 | grep "\-y, --yes"` ]]; then
		rm /etc/apt/sources.list.d/"$first"-"$second"-*.list
	fi
fi
ERRORGETTINGKEY=$(cat /tmp/.added_ppa | tail -n 1 | grep ^gpg.*0$)
if [[ "$ERRORGETTINGKEY" ]]; then
	GPGKEYTOGET=$(cat /tmp/.added_ppa | grep "recv" | cut -d' ' -f17)
	gpg --ignore-time-conflict --no-options --no-default-keyring --secret-keyring /etc/apt/secring.gpg --trustdb-name /etc/apt/trustdb.gpg --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv $GPGKEYTOGET
fi

#rm /tmp/.added_ppa > /dev/null 2>&1
}


function find_n_remove_dupes() {

checkAPT

rm /tmp/.dupes_to_remove /tmp/.dupes_show /tmp/.rmdups > /dev/null 2>&1

finddupes=$(unset flist; declare -A flist
while read -r sum fname; do
    if [[ ${flist[$sum]} ]]; then
        printf 'sudo rm -- "%s" # Same as >%s<\n' "$fname" "${flist[$sum]}" 
    else
        flist[$sum]="$fname"
    fi
done <  <(find /etc/apt/sources.list.d/ -name "*.list" -exec sha256sum {} +)  >/tmp/.rmdups)
dupes_number=$(cat /tmp/.rmdups | wc -l)
cp /tmp/.rmdups /tmp/.dupes_show
sed -i -e 's/sudo rm -- "/   /g' -e 's/" # Same as >/ is the same as: \n   /g' -e 's/list</list \n/g' /tmp/.dupes_show
dupes_show=$(cat /tmp/.dupes_show)
cp /tmp/.rmdups /tmp/.dupes_to_remove
sed -i -e 's/sudo rm -- "/   /g' -e 's/" #.*//g' -e 's/$list/list \n/g' /tmp/.dupes_to_remove
dupes_to_remove=$(cat /tmp/.dupes_to_remove)

if [[ -s /tmp/.rmdups ]]; then
	yad --center --class="y-ppa-manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --form --title="Duplicate PPA sources detected" --text="   You have $dupes_number duplicate PPA source list file(s)   " --button="gtk-cancel:1" --button="Remove duplicates:0" --button="Show duplicates:2"
	ret=$?
	if [[ $ret -eq 0 ]]; then
		chmod +x /tmp/.rmdups
		sh /tmp/.rmdups && rm /tmp/.dupes_to_remove /tmp/.dupes_show /tmp/.rmdups > /dev/null 2>&1
		su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=dialog-ok \"Y PPA Manager - Done\" \"Successfully removed duplicates\""

	elif [[ $ret -eq 2 ]]; then
		yad --center --class="y-ppa-manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --form --title="Duplicate PPA sources" --text="$dupes_show \n\n\n   <b>The following PPA source(s) will be removed:</b> \n$dupes_to_remove"   --button="gtk-cancel:1" --button="Remove duplicates:0"
		if [[ $? -eq 0 ]]; then
			chmod +x /tmp/.rmdups
			sh /tmp/.rmdups && rm /tmp/.dupes_to_remove /tmp/.dupes_show /tmp/.rmdups > /dev/null 2>&1
			su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=dialog-ok \"Y PPA Manager - Done\" \"Successfully removed duplicates\""
		else
			advanced_options
		fi

	else
		advanced_options

	fi
else
	su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=dialog-information \"Y PPA Manager\" \"No PPA duplicates found\""
	echo no dupes found
fi

advanced_options
}

add_a_PPA()  
{
	
#	checkAPT

	ADD_PPA=`yad --center --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --entry --title="Add a PPA" --text="\n Enter a PPA to add (e.g.: ppa:webupd8team/ghtumb) \n" --entry-label="PPA:"`
	

	if [[ $? -eq 0 ]]; then
	
		ADD_PPA_NO_SPACES=`echo "$ADD_PPA" | sed -e "s/ //g"`
		
		valid_ppa_check1=$(echo "$ADD_PPA_NO_SPACES" | grep "^ppa:")
		valid_ppa_check2=$(echo "$ADD_PPA_NO_SPACES" | sed -e "s/^ppa://g" | grep "/")
		valid_ppa_check3=$(echo "$ADD_PPA_NO_SPACES" | sed -e "s/^ppa://g" | cut -d '/' -f 1 | wc -c)
		valid_ppa_check4=$(echo "$ADD_PPA_NO_SPACES" | sed -e "s/^ppa://g" | cut -d '/' -f 2 | wc -c)
		valid_ppa_check5=$(echo "$ADD_PPA_NO_SPACES" | tr -cd "/" | wc -c)
		valid_ppa_check6=$(echo "$ADD_PPA_NO_SPACES" | tr -cd ":" | wc -c)		
		
		if [[ "$ADD_PPA_NO_SPACES" && $valid_ppa_check1 && $valid_ppa_check2 && $valid_ppa_check3 -gt 0 && $valid_ppa_check4 -gt 0 && $valid_ppa_check5 -eq 1 && $valid_ppa_check6 -eq 1 ]]; then

#check if PPA is already added or not
			ppafilename1=`echo "$ADD_PPA_NO_SPACES" | sed -e "s/\//-/g" -e "s/ //g"`
			ppafilename2=`echo "$ADD_PPA_NO_SPACES" | sed -e "s/\//-/g" -e "s/ //g"`
			username="$(echo $ADD_PPA_NO_SPACES | cut -f1 -d\/ | cut -f2 -d\:)"
			ppaname="$(echo $ADD_PPA_NO_SPACES | cut -f2 -d\/)"
			checkinppaa=`cat /etc/apt/sources.list.d/*.list | grep -i "deb http://ppa.launchpad.net/$username/$ppaname/ubuntu"`
			checksourceslist=`cat /etc/apt/sources.list | grep -i "deb http://ppa.launchpad.net/$username/$ppaname/ubuntu"`
			
			if [[ -e /etc/apt/sources.list.d/"$ppafilename1".list || -e /etc/apt/sources.list.d/"$ppafilename2"-$UBUVER\.list || $checkinppaa || $checksourceslist ]]; then
				yad --center --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --form --title="Error - Y PPA Manager" --text="  The ppa:$ADD_PPA_NO_SPACES is already  \n  added on your system.  " --button="gtk-ok:0"
				add_a_PPA
			fi
#done check


#			checkAPT
			su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=list-add \"Y PPA Manager\" \"Adding \"$ADD_PPA_NO_SPACES\"\""
			y_add_ppa "$ADD_PPA_NO_SPACES"
			#apt-get update
			
			ppafilename1=`echo "$ADD_PPA_NO_SPACES" | sed -e "s/^ppa://g" -e "s/\//-/g"`
			ppafilename2=`echo "$ADD_PPA_NO_SPACES" | sed -e "s/^ppa://g" -e "s/\//-/g"`
			username="$(echo $ADD_PPA_NO_SPACES | cut -f1 -d\/ | cut -f2 -d\:)"
			ppaname="$(echo $ADD_PPA_NO_SPACES | cut -f2 -d\/)"
			checkinppa=`cat /etc/apt/sources.list.d/*.list | grep -i "deb http://ppa.launchpad.net/$username/$ppaname/ubuntu"`
			checksourceslist=`cat /etc/apt/sources.list | grep -i "deb http://ppa.launchpad.net/$username/$ppaname/ubuntu"`
			
			if [[ -e /etc/apt/sources.list.d/"$ppafilename1".list || -e /etc/apt/sources.list.d/"$ppafilename2"-$UBUVER\.list || $checkinppa || $checksourceslist ]]; then
				su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=list-add \"Y PPA Manager - Done\" \"The \"$ADD_PPA_NO_SPACES\" PPA has been added successfully\""
			else
				su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=dialog-error \"Y PPA Manager\" \"An error occured and \"$ADD_PPA_NO_SPACES\" has not been added\""
			
			fi	
		
		else
			yad --center --class="y-ppa-manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --form --title="Error" --text="  The PPA you've entered is not valid  \n  Please enter a valid PPA (e.g.: ppa:webupd8/gthumb)  " --button="gtk-ok:0"
			add_a_PPA
		fi	
	else
		exit
	fi
}



list_packages_PPA()
{
	CLEARTEMP
	touch /tmp/.non_disabled.list

	rm /tmp/.Packages > /dev/null 2>&1;

	list_sourcesLIST=`ls /etc/apt/sources.list.d | grep .list$ > /tmp/.temp_sources.list ; cat /tmp/.temp_sources.list`

	cat /tmp/.temp_sources.list
	IFS=$'\n'
	n=1
	while read curline; do
		ppa_disabled_lp_check=`cat /etc/apt/sources.list.d/"$curline" | sed -e 's/^deb-src.*//g' -e '/^$/d' | grep -v "^[[:space:]]*\(#.*\)\?$" | grep "http://ppa.launchpad.net"`

		if [[ $ppa_disabled_lp_check ]]; then
			ppausername=$(cat /etc/apt/sources.list.d/"$curline" | grep "^deb http://ppa.launchpad.net" | sed -e 's/deb http:\/\/ppa.launchpad.net//g' -e 's/$ main//g' | cut -d '/' -f2)
			ppaname=$(cat /etc/apt/sources.list.d/"$curline" | grep "^deb http://ppa.launchpad.net" | sed -e 's/deb http:\/\/ppa.launchpad.net//g' -e 's/$ main//g' | cut -d '/' -f3)
			ppaubuver=$(cat /etc/apt/sources.list.d/"$curline" | grep "^deb http://ppa.launchpad.net" | sed -e 's/deb http:\/\/ppa.launchpad.net//g' -e 's/$ main//g' | cut -d ' ' -f2)
			if [[ $ppausername ]]; then
				echo "ppa:$ppausername/$ppaname ($ppaubuver)" | tee -a /tmp/.y_ppalist.list > /dev/null 2>&1;
			fi
		fi
		let n=n+1
	done < /tmp/.temp_sources.list


	#list_sourcesNAMES=`cat /tmp/.non_disabled.list`
#trying to fix -ubuntuversion not existing
#	cat /tmp/.non_disabled.list

#	while read curline; do
#		is_launchpad_ppa=`cat /etc/apt/sources.list.d/"$curline".list | grep "http://ppa.launchpad.net"`
#echo $curline
#		if [[ $is_launchpad_ppa ]]; then
#			echo "$curline" | tee -a /tmp/.real_lp_ppas2.list > /dev/null 2>&1;
#		fi
#		let n=n+1
#	done < /tmp/.non_disabled.list



	#add PPAs from /etc/apt/sources.list
	IFS=$'\n'
	n=1
	while read curline; do
		ppausername=$(echo "$curline" | grep "^deb http://ppa.launchpad.net" | sed -e 's/deb http:\/\/ppa.launchpad.net//g' -e 's/$ main//g' | cut -d '/' -f2)
		ppaname=$(echo "$curline" | grep "^deb http://ppa.launchpad.net" | sed -e 's/deb http:\/\/ppa.launchpad.net//g' -e 's/$ main//g' | cut -d '/' -f3)
		ppaubuver=$(echo "$curline" | grep "^deb http://ppa.launchpad.net" | sed -e 's/deb http:\/\/ppa.launchpad.net//g' -e 's/$ main//g' | cut -d ' ' -f2)
		if [[ $ppausername ]]; then
			echo "ppa:$ppausername/$ppaname ($ppaubuver)" | tee -a /tmp/.y_ppalist.list > /dev/null 2>&1;
		fi

		let n=n+1
	done < /etc/apt/sources.list


	list_sourcesNAMES=$(cat /tmp/.y_ppalist.list)
#	list_sourcesNAMES=`cat /tmp/.non_disabled.list`

	LIST_PPA_PACKAGES=$(yad --center --always-print-result --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --separator="" --list --width=600 --height=500 --title="Manage PPAs - Y PPA Manager" --search-column="1" --regex-search --text="Select the PPA from the list below (only non-disabled PPAs are listed):" --button="Remove:4" --button="Purge:5" --button="Update:2" --button="Edit source:3" --button="List packages:0" --button="Close:6" --column "PPA" --list $list_sourcesNAMES)
	ret=$?
	echo LIST_PPA_PACKAGES $LIST_PPA_PACKAGES

	stripppa=$(echo "$LIST_PPA_PACKAGES" | sed -e 's/ppa://g')
	ppausername=$(echo "$stripppa" | cut -f1 -d/)
	ppaname=$(echo "$stripppa" | sed -e 's/ (.*//g' | cut -f2 -d/)
	ubuntudist=$(echo "$stripppa" | cut -f2 -d ' ' | sed -e 's/(//g' -e 's/)//g')
	ppa_temp_url=http://ppa.launchpad.net/$ppausername/$ppaname/ubuntu/dists/$ubuntudist/main

	if [[ $ret -eq 0 ]]; then

		if [[ "i686" = `uname -m` ]]; then
			arch=i386
		elif [[ "x86_64" = `uname -m` ]]; then
			arch=amd64
		else
       			echo You are not using Ubuntu 32bit or 64bit, exiting
       			exit
   		fi
   	
   		testConnection
   		cd /tmp/
		wget --no-check-certificate "$ppa_temp_url"/binary-$arch/Packages
		if [[ ! -e Packages ]]; then
			wget --no-check-certificate -q "$ppa_temp_url"/binary-$arch/Packages.gz
			gzip -d Packages.gz
			rm -f Packages.gz
		fi
		mv Packages .Packages
		#echo  $ppa_temp_url/binary-$arch/Packages


		PPA_PACKAGES=`grep "^Package: " .Packages | sed -e 's/Package://g' > .packagename2`
		PPA_VERSIONS=`grep "^Version: "  .Packages |  sed -e 's/Version://g' -e 's/$/)/g' -e 's/^ /(/g' > .packageversion2`

		paste --delimiters=" " .packagename2 .packageversion2 > .package_search_list_results2

		PPA_SEARCH_LIST_RESULTS2=`cat .package_search_list_results2`

		url_part_1=`echo "$ppa_temp_url" | cut -d '/' -f 4`
		url_part_2=`echo "$ppa_temp_url" | cut -d '/' -f 5`
		ppa_name=""$url_part_1"/"$url_part_2""

		#ZENITY_PPA_PACKAGES="$PPA_PACKAGES ($PPA_VERSIONS)"

		LIST_PACKAGES=`yad --center --class="Y-PPA-Manager" --name="Y PPA Manager" --always-print-result --multiple --separator=" " --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --width=500 --height=250 --title="Packages - Y PPA Manager" --search-column="1" --regex-search --button="Back:1" --button="Copy PPA link to clipboard:0" --text="  Packages in "$ppa_name" PPA (for your Ubuntu version only!): " --column="Package (version)" --list $PPA_SEARCH_LIST_RESULTS2`
		ret=$?
		if [[ $ret -eq 0 ]]; then	

		
			#echo "http://launchpad.net/~"$url_part_1"/+archive/"$url_part_2"" | xclip -selection clipboard
			#sudo -u "$loggeduser" notify-send -h int:transient:1 -t 10000 -u normal --expire-time="8000" --icon=gtk-paste "Y PPA Manager" ""$ppa_name" PPA link has been copied to the clipboard. Paste the link (CTRL + V) in a web browser."
			#open PPA link in browser:
			su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=dialog-info \"Y PPA Manager - Link copied to clipboard\" \"The PPA link has been copied to the clipboard. Paste the link in a web browser using CTRL + V.\""; echo -n http://launchpad.net/~"$url_part_1"/+archive/"$url_part_2" | xclip -selection clipboard
			########
			CLEARTEMP
			list_packages_PPA
	
		elif [[ $ret -eq 1 ]]; then
			CLEARTEMP	
			list_packages_PPA
		fi	

		CLEARTEMP
	elif [[ $ret -eq 2 ]]; then

		fullppa_stripdist=$(echo "$LIST_PPA_PACKAGES" | sed -e 's/ (.*//g')
		update-ppa "$fullppa_stripdist"
		CLEARTEMP
		su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=list-add \"Y PPA Manager\" \"The \"$fullppa_stripdist\" PPA source has been updated successfully\""
		list_packages_PPA

	elif [[ $ret -eq 3 ]]; then

		stripppa=$(echo "$LIST_PPA_PACKAGES" | sed -e 's/ppa://g')
		ppausername=$(echo "$stripppa" | cut -f1 -d/)
		ppausername_charfix=$(echo "$stripppa" | cut -f1 -d/ | sed -e 's/[.+]/_/g')
		ppaname_charfix=$(echo "$stripppa" | sed -e 's/ (.*//g' | cut -f2 -d/ | sed -e 's/[.+]/_/g')
		ppaname=$(echo "$stripppa" | sed -e 's/ (.*//g' | cut -f2 -d/)
		ubuntudist=$(echo "$stripppa" | cut -f2 -d ' ' | sed -e 's/(//g' -e 's/)//g')
		if [[ `cat /etc/apt/sources.list.d/*.list | grep -i "deb http://ppa.launchpad.net/$ppausername/$ppaname/ubuntu"` ]]; then
			if [ -f /etc/apt/sources.list.d/$ppausername_charfix-$ppaname_charfix-*.list ]; then
				xdg-open /etc/apt/sources.list.d/$ppausername_charfix-$ppaname_charfix-*.list
			else
				xdg-open /etc/apt/sources.list.d/$ppausername_charfix-ubuntu-$ppaname_charfix-*.list
			fi
		else
			xdg-open /etc/apt/sources.list
		fi
		CLEARTEMP
		list_packages_PPA

	elif [[ $ret -eq 4 ]]; then
		stripppa=$(echo "$LIST_PPA_PACKAGES" | sed -e 's/ppa://g')
		ppausername=$(echo "$stripppa" | cut -f1 -d/)
		ppaname=$(echo "$stripppa" | sed -e 's/ (.*//g' | cut -f2 -d/)
		ppausername_charfix=$(echo "$stripppa" | cut -f1 -d/ | sed -e 's/[.+]/_/g')
		ppaname_charfix=$(echo "$stripppa" | sed -e 's/ (.*//g' | cut -f2 -d/ | sed -e 's/[.+]/_/g')
		ubuntudist=$(echo "$stripppa" | cut -f2 -d ' ' | sed -e 's/(//g' -e 's/)//g')
		fullppa_stripdist=$(echo "$LIST_PPA_PACKAGES" | sed -e 's/ (.*//g')

        	su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=list-remove \"Y PPA Manager\" \"Removing \"$fullppa_stripdist\" and updating software sources\""
		echo "the ls command looks like this: /etc/apt/sources.list.d/$ppausername_charfix-$ppaname_charfix-*.list"

		if [[ `ls /etc/apt/sources.list.d/$ppausername_charfix-$ppaname_charfix-*.list` ]]; then
			if [ -f /etc/apt/sources.list.d/$ppausername_charfix-$ppaname_charfix-*.list ]; then
				rm /etc/apt/sources.list.d/$ppausername_charfix-$ppaname_charfix-*.list && apt-get update
			fi
		elif [[ `ls /etc/apt/sources.list.d/$ppausername_charfix-ubuntu-$ppaname_charfix-*.list` ]]; then
			if [ -f /etc/apt/sources.list.d/$ppausername_charfix-ubuntu-$ppaname_charfix-*.list ]; then
				rm /etc/apt/sources.list.d/$ppausername_charfix-ubuntu-$ppaname_charfix-*.list && apt-get update
			fi

		else
			sed -i "/$ppausername.*$ppaname\/ubuntu $ubuntudist.*/d" /etc/apt/sources.list && apt-get update
		fi



		rm /tmp/.temp_sourcesnames2.list /tmp/.temp_sources2.list /tmp/.non_disabled2.list > /dev/null 2>&1;
		su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=list-remove \"Y PPA Manager - Done\" \"Removed PPA: \"$fullppa_stripdist\" successfully\""

		CLEARTEMP
		list_packages_PPA

	elif [[ $ret -eq 5 ]]; then

		stripppa=$(echo "$LIST_PPA_PACKAGES" | sed -e 's/ppa://g')
		ppausername=$(echo "$stripppa" | cut -f1 -d/)
		ppaname=$(echo "$stripppa" | sed -e 's/ (.*//g' | cut -f2 -d/)
		ubuntudist=$(echo "$stripppa" | cut -f2 -d ' ' | sed -e 's/(//g' -e 's/)//g')
		fullppa_stripdist=$(echo "$LIST_PPA_PACKAGES" | sed -e 's/ (.*//g')

		yad --center --class="y-ppa-manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --form --title="Confirm" --text="  Are you sure you want to purge  \n  the "$fullppa_stripdist" PPA?   " --button="Cancel:1" --button="OK:0"
		if [[ $? -eq 0 ]]; then
			checkAPT
			testConnection
			#xterm -hold -e ppa-purge ppa:$the_ppa_to_purge
			PPA_PURGE_AUTO=`grep "ppa-purge=auto" /etc/y-ppa-manager.conf`
				
			if [[ $PPA_PURGE_AUTO ]]; then
				su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=list-remove \"Y PPA Manager\" \"Please wait while purging \"$fullppa_stripdist\"\""
				if [[ `lsb_release -cs` = "helena" || `lsb_release -cs` = "isadora" || `lsb_release -cs` = "julia" || `lsb_release -cs` = "katya" || `lsb_release -cs` = "lisa" || `lsb_release -cs` = "maya" || `lsb_release -cs` = "nadia" || `lsb_release -cs` = "olivia" || `lsb_release -cs` = "petra" || `lsb_release -cs` = "qiana" || `lsb_release -cs` = "rebecca" || `lsb_release -cs` = "rafaela" || `lsb_release -cs` = "rosa" || `lsb_release -cs` = "sarah"  || `lsb_release -cs` = "serena" || `lsb_release -cs` = "sonya" || `lsb_release -cs` = "tara" || `lsb_release -cs` = "luna" || `lsb_release -cs` = "freya" || `lsb_release -cs` = "loki" || `lsb_release -cs` = "juno" || `lsb_release -cs` = "hera" || `lsb_release -cs` = "odin" || `lsb_release -cs` = "tessa" || `lsb_release -cs` = "tina" || `lsb_release -cs` = "tricia" || `lsb_release -cs` = "ulyana" || `lsb_release -cs` = "ulyssa" || `lsb_release -cs` = "uma" ]]; then
					sudo ppa-purge -d $UBUVER -y "$fullppa_stripdist"
				else
					sudo ppa-purge -y "$fullppa_stripdist"
				fi
			else
				su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=list-remove \"Y PPA Manager\" \"Close the terminal window when you are done purging\""
				if [[ `lsb_release -cs` = "helena" || `lsb_release -cs` = "isadora" || `lsb_release -cs` = "julia" || `lsb_release -cs` = "katya" || `lsb_release -cs` = "lisa" || `lsb_release -cs` = "maya" || `lsb_release -cs` = "nadia" || `lsb_release -cs` = "olivia" || `lsb_release -cs` = "petra" || `lsb_release -cs` = "qiana" || `lsb_release -cs` = "rebecca" || `lsb_release -cs` = "rafaela" || `lsb_release -cs` = "rosa" || `lsb_release -cs` = "sarah"  || `lsb_release -cs` = "serena" || `lsb_release -cs` = "sonya" || `lsb_release -cs` = "sylvia" || `lsb_release -cs` = "tara" || `lsb_release -cs` = "luna" || `lsb_release -cs` = "freya" || `lsb_release -cs` = "loki" || `lsb_release -cs` = "juno" || `lsb_release -cs` = "hera" || `lsb_release -cs` = "odin" || `lsb_release -cs` = "tessa" || `lsb_release -cs` = "tina" || `lsb_release -cs` = "tricia" || `lsb_release -cs` = "ulyana" || `lsb_release -cs` = "ulyssa" || `lsb_release -cs` = "uma" ]]; then
					xterm -hold -e sudo ppa-purge -d $UBUVER $fullppa_stripdist
				else					
					xterm -hold -e sudo ppa-purge $fullppa_stripdist
				fi
			fi
			su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=list-remove \"Y PPA Manager - Done\" \"Purged  \"$fullppa_stripdist\"\""
			rm /tmp/.temp_sourcesnames2.list /tmp/.temp_sources2.list /tmp/.non_disabled2.list > /dev/null 2>&1
			list_packages_PPA
		else
			list_packages_PPA
		
		fi

	else
		CLEARTEMP
		exit
		
	fi

}



function y_ppa_backup() {

b_name=$(date +%F-%H%M)
username=$(cat /tmp/.yppa_username)
homedir=$(cat /tmp/.yppa_home)

Y_PPA_BACKUP=`yad --center --class="Y-PPA-Manager" --name="Y PPA Manager" --file-selection --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --filename=$homedir/repositories.backup-$b_name.tar.gz --save  --button="Cancel:1" --button="Save:0" --width=700 --height=500 --title="Save the backup..."`

ret=$?
if [[ $ret -eq 0 ]]; then
	cp -r /etc/apt/sources.list.d/ /tmp/.sources
	grep "ppa.launchpad.net" /etc/apt/sources.list >> /tmp/.sources/sourceslist.ppas
	cd /tmp/.sources/
	tar czvf "repositories.backup-$b_name.tar.gz" *
	cp /tmp/.sources/repositories.backup-$b_name.tar.gz "$Y_PPA_BACKUP"
	cd -
	rm -r /tmp/.sources
	chown "$username" "$Y_PPA_BACKUP"

	if [ -e "$Y_PPA_BACKUP" ]; then
		su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=dialog-ok \"Y PPA Manager\" \"Repositories backup successfully created\""
	else
		su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=dialog-error \"Y PPA Manager\" \"Error: backup failed.\""
	fi
	
else
	CLEARTEMP
	exit
fi
advanced_options
}

#function y_full_backup() {

#b_name=$(date +%F-%H%M)

#Y_PPA_BACKUP=`yad --center --class="Y-PPA-Manager" --name="Y PPA Manager" --file-selection --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --filename=/home/$ON_USER/full-sources.backup-$b_name.tar.gz --save  --button="Cancel:1" --button="Save:0" --width=700 --height=500 --title="Save the backup..."`

#if [[ $? -eq 0 ]]; then
#	cd /etc/apt/
#	gksu -S -m "Y PPA Manager requires admin privileges for this task" tar czvf full-sources.backup-$b_name.tar.gz *
#	cp /etc/apt/full-sources.backup-$b_name.tar.gz "$Y_PPA_BACKUP"
#	cd -
#	gksu -S rm /etc/apt/full-sources.backup-$b_name.tar.gz
#	sudo -u "$loggeduser" notify-send -h int:transient:1 -t 10000 -u normal --expire-time="3000" --icon=list-add "Y PPA Manager" "Full sources backup successfully created"
#else
#	CLEARTEMP
#	exit
#fi
#advanced_options
#}


function y_ppa_restore() {
username=`who | grep "$DISPLAY" | cut -d ' ' -f 1 | tail -1`
homedir=`awk -F: -v v="$username" '{if ($1==v) print $6}' /etc/passwd`
Y_PPA_BACKUP=`yad --center --class="Y-PPA-Manager" --name="Y PPA Manager" --file-selection --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --save --filename=$homedir/ --button="Cancel:1" --button="Restore:0" --width=700 --height=500 --title="Select backup to restore..."`	

if [[ $? -eq 0 ]]; then
	tar zxvf "$Y_PPA_BACKUP" -C /etc/apt/sources.list.d/
	cat /etc/apt/sources.list.d/sourceslist.ppas
	while read line
	do
		LINEEXISTS=$(grep "$line" /etc/apt/sources.list)
		if [[ ! "$LINEEXISTS" ]]; then
			echo "$line" >> /etc/apt/sources.list
		fi
	done < /etc/apt/sources.list.d/sourceslist.ppas
	rm /etc/apt/sources.list.d/sourceslist.ppas
	launchpad-getkeys

	su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=document-save \"Y PPA Manager\" \"Repositories backup successfully restored. It is advisable to run an update now\""
else
	CLEARTEMP
	exit
fi

advanced_options
}


function y_ppa_upgrade_regular() {
ppa-upgrade -r
}

function y_ppa_upgrade_replace() {
ppa-upgrade -u
}


function y_ppa_import_gpg_keys() {

	Y_UPGRADE_PPA=`yad --center --form --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --text="   Will try to import all missing GPG repository keys.   \n   This make take a a while so please be patient.   \n\n   Click OK to continue   " --button="gtk-cancel:1" --button="gtk-ok:0"`
	ret=$?
	if [[ $ret -eq 0 ]]; then
		launchpad-getkeys

		su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=object-flip-vertical \"Y PPA Manager\" \"Done importing missing GPG keys\""
		y-ppa-cmd advanced
	else
		y-ppa-cmd advanced
	fi

}


function y_ppa_fix_gpg_badsig() {

	Y_UPGRADE_PPA=`yad --center --form --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --text="   Will try to fix all GPG BADSIG errors.   \n   This make take a a while so please be patient.   \n\n   Click OK to continue   " --button="gtk-cancel:1" --button="gtk-ok:0"`
	ret=$?
	if [[ $ret -eq 0 ]]; then
		fix_gpg_badsig

		su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=object-flip-vertical \"Y PPA Manager\" \"Done fixing GPG BADSIG errors\""
		y-ppa-cmd advanced
	else
		y-ppa-cmd advanced
	fi

}

#function y_full_restore() {
#Y_PPA_BACKUP=`yad --center --file-selection --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --save  --button="Cancel:1" --button="Restore:0" --width=700 --height=500 --title="Select a full backup to restore..."`	

#if [[ $? -eq 0 ]]; then
#	gksu -S -m "Y PPA Manager requires admin privileges for this task" "tar -xvf "$Y_PPA_BACKUP" -C /etc/apt/"
#	sudo -u "$loggeduser" notify-send -h int:transient:1 -t 10000 -u normal --expire-time="3000" --icon=list-add "Y PPA Manager" "Full sources backup successfully restored. It's advisable to run an update now"
#else
#	CLEARTEMP
#	exit
#fi

#advanced_options
#}

function advanced_options() {

Y_ADVANCED=`yad --center --list --no-headers --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --column="" "Scan and remove duplicate PPAs" "Try to import all missing GPG keys" "Try to fix all GPG BADSIG errors" "Backup repositories" "Restore repositories backup" "Re-enable working PPAs after Ubuntu upgrade" "Update release name in working PPAs" --width=350 --height=270 --title="Advanced - Y PPA Manager" --button="Close:1" --button="gtk-ok:0"`

Y_ADVANCED_fix=`echo "$Y_ADVANCED" | sed -e "s/|//"`

if [[ $? -eq 0 ]]; then
	if [[ $Y_ADVANCED_fix = "Backup repositories" ]]; then
		y_ppa_backup
	elif [[ $Y_ADVANCED_fix = "Scan and remove duplicate PPAs" ]]; then
		find_n_remove_dupes
	elif [[ $Y_ADVANCED_fix = "Try to import all missing GPG keys" ]]; then
		y_ppa_import_gpg_keys
	elif [[ $Y_ADVANCED_fix = "Try to fix all GPG BADSIG errors" ]]; then
		y_ppa_fix_gpg_badsig
	elif [[ $Y_ADVANCED_fix = "Restore repositories backup" ]]; then
		y_ppa_restore
	elif [[ $Y_ADVANCED_fix = "Re-enable working PPAs after Ubuntu upgrade" ]]; then
		y_ppa_upgrade_regular
	elif [[ $Y_ADVANCED_fix = "Update release name in working PPAs" ]]; then
		y_ppa_upgrade_replace
	else
		CLEARTEMP
		exit

	fi
else
	CLEARTEMP
	exit
fi

}



function reset_settings() {

#	DOWN_DIR=`cat /home/$ON_USER/.config/user-dirs.dirs | grep XDG_DOWNLOAD_DIR | sed -e 's/XDG_DOWNLOAD_DIR="$HOME\///g' -e 's/"//g'`

#	gksu -S -m "Y PPA Manager requires admin privileges for this task" rm /etc/y-ppa-manager.conf
	
	echo "#ppa-purge behavior: auto - don't require any user input; manual - opens a terminal window asking the user how to solve the issue (this is the default behavior). Set manual/auto below:" > /tmp/.y-ppa-manager.conf
	echo "ppa-purge=manual" >> /tmp/.y-ppa-manager.conf
	echo $'\n' >> /tmp/.y-ppa-manager.conf
	echo "#By default, the integrated PPA Search will display packages for your Ubuntu version. However, you can change this below:" >> /tmp/.y-ppa-manager.conf
	echo "searchdist=$UBUVER" >> /tmp/.y-ppa-manager.conf
	echo $'\n' >> /tmp/.y-ppa-manager.conf
#	echo "#Use Ubuntu Indicator (default: disabled):" >> /tmp/.y-ppa-manager.conf
#	echo "indicator=disabled" >> /tmp/.y-ppa-manager.conf
#	echo $'\n' >> /tmp/.y-ppa-manager.conf
#	echo "#Downloads folder (default: /home/$ON_USER/$DOWN_DIR/y-ppa-manager):" >> /tmp/.y-ppa-manager.conf
#	echo "downloads=/home/$ON_USER/$DOWN_DIR/y-ppa-manager" >> /tmp/.y-ppa-manager.conf
	echo $'\n' >> /tmp/.y-ppa-manager.conf
	echo "rankings=false" >> /tmp/.y-ppa-manager.conf

	rm /etc/y-ppa-manager.conf; cp /tmp/.y-ppa-manager.conf /etc/y-ppa-manager.conf
	rm /tmp/.y-ppa-manager.conf
#	rm /etc/xdg/autostart/y-ppa-indicator.desktop

	su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=view-refresh \"Y PPA Manager\" \"Settings were reset\""

}

function y_ppa_settings() {

current_ubuntu_version=`grep "searchdist=" /etc/y-ppa-manager.conf | sed -e 's/searchdist=//g'`
current_ppa_purge=`grep "ppa-purge=" /etc/y-ppa-manager.conf | sed -e 's/ppa-purge=//g'`
#current_indicator=`grep "indicator=" /etc/y-ppa-manager.conf | sed -e 's/indicator=//g'`
#current_downloads_folder=`grep "downloads=" /etc/y-ppa-manager.conf | sed -e "s/downloads=//g"`
#temporarely_disabled current_rankings=`grep "rankings=" /etc/y-ppa-manager.conf | sed -e 's/rankings=//'`

if [[ $current_ppa_purge = "auto" ]]; then
	ppa_purge_opt="auto!manual"
elif [[ $current_ppa_purge = "manual" ]]; then
	ppa_purge_opt="manual!auto"
fi

#if [[ $current_indicator = "disabled" ]]; then
#	indicator_opt="disabled!enabled!stand-alone"
#elif [[ $current_indicator = "enabled" ]]; then
#	indicator_opt="enabled!disabled!stand-alone"
#elif [[ $current_indicator = "stand-alone" ]]; then
#	indicator_opt="stand-alone!enabled!disabled"
#fi

#temporarely_disabled  if [[ $current_rankings = "false" ]]; then
#temporarely_disabled  	rankings_opt="false!true"
#temporarely_disabled  elif [[ $current_rankings = "true" ]]; then
#temporarely_disabled  	rankings_opt="true!false"
#temporarely_disabled  fi


#temporarely_disabled  Y_SETTINGS=`yad --center --form --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --field="PPA-Purge:CB" $ppa_purge_opt --field="Display PPA rankings for deep search (slow):CB" $rankings_opt --field="Ubuntu version*" "$current_ubuntu_version" --field="Downloads folder:DIR" "$current_downloads_folder" --text="   * Linux Mint users - enter the corresponding Ubuntu version   " --button="Reset to default:2" --button="gtk-cancel:1" --button="gtk-ok:0"`

#Y_SETTINGS=`yad --center --form --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --title="Settings - Y PPA Manager" --field="PPA-Purge:CB" $ppa_purge_opt --field="Ubuntu Indicator:CB" $indicator_opt --field="Ubuntu version*" "$current_ubuntu_version" --text="   * Linux Mint, elementary OS users - enter the corresponding Ubuntu version   " --button="Reset to default:2" --button="gtk-cancel:1" --button="gtk-ok:0"`
Y_SETTINGS=`yad --center --form --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --title="Settings - Y PPA Manager" --field="PPA-Purge:CB" $ppa_purge_opt --field="Ubuntu version*" "$current_ubuntu_version" --text="   * Linux Mint, elementary OS users - enter the corresponding Ubuntu version   " --button="Reset to default:2" --button="gtk-cancel:1" --button="gtk-ok:0"`

ret=$?

#echo indicator_opt $indicator_opt
#echo ppa_purge_opt $ppa_purge_opt
#echo current_ubuntu_version $current_ubuntu_version
#echo current_downloads_folder $current_downloads_folder
#echo Y_SETTINGS $Y_SETTINGS

if [[ $ret -eq 0 ]]; then
	Y_purge=`echo "$Y_SETTINGS" | cut -d '|' -f1`
	#Y_indicator=`echo "$Y_SETTINGS" | cut -d '|' -f2`
#temporarely_disabled 	Y_rank=`echo "$Y_SETTINGS" | cut -d '|' -f2`
#temporarely_disabled 	Y_dist=`echo "$Y_SETTINGS" | cut -d '|' -f3`
#temporarely_disabled 	Y_down=`echo "$Y_SETTINGS" | cut -d '|' -f4`
#here, they must be from -f1 to -f4
#	Y_dist=`echo "$Y_SETTINGS" | cut -d '|' -f3`
	Y_dist=`echo "$Y_SETTINGS" | cut -d '|' -f2`
#	Y_down=`echo "$Y_SETTINGS" | cut -d '|' -f3`

	cp /etc/y-ppa-manager.conf /tmp/.y-ppa-manager.conf

	if [[ $Y_purge != $current_ppa_purge ]]; then

		sed -i "s/ppa-purge=.*/ppa-purge=$Y_purge/g" /tmp/.y-ppa-manager.conf
#		gksu -S -m "Y PPA Manager requires admin privileges for this task" cp /tmp/.y-ppa-manager.conf /etc/y-ppa-manager.conf
#		rm /tmp/.y-ppa-manager.conf
	fi

#	if [[ "$Y_indicator" != "$current_indicator" ]]; then
#	echo $Y_indicator Y_indicator

#		sed -i "s/indicator=.*/indicator=$Y_indicator/g" /tmp/.y-ppa-manager.conf
#		gksu -S -m "Y PPA Manager requires admin privileges for this task" cp /tmp/.y-ppa-manager.conf /etc/y-ppa-manager.conf
#		rm /tmp/.y-ppa-manager.conf
#		if [[ $Y_indicator = "stand-alone" ]]; then
#			echo "
#[Desktop Entry]
#Type=Application
#Exec="/usr/bin/y-ppa-indicator"
#Hidden=false
#NoDisplay=false
#X-GNOME-Autostart-enabled=true
#Name=Y PPA Manager Indicator
#Comment=Stand-alone Y PPA Manager Ubuntu indicator" > /etc/xdg/autostart/y-ppa-indicator.desktop

#		elif [[ $Y_indicator = "enabled" ]]; then
#			rm /etc/xdg/autostart/y-ppa-indicator.desktop > /dev/null 2>&1
#			yad --center --form --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --text="   The indicator will be started the   \n   next time you run Y PPA Manager   " --button="Ok:1"

#		elif [[ $Y_indicator = "disabled" ]]; then
#			killall y-ppa-indicator &
#			rm /etc/xdg/autostart/y-ppa-indicator.desktop > /dev/null 2>&1
#		fi

#	fi
	
	if [[ $Y_dist != $current_ubuntu_version ]]; then

		if [[ $Y_dist = "karmic" || $Y_dist = "lucid" || $Y_dist = "maverick" || $Y_dist = "natty" || $Y_dist = "oneiric" || $Y_dist = "precise" || $Y_dist = "quantal" || $Y_dist = "raring" || $Y_dist = "saucy" || $Y_dist = "trusty" || $Y_dist = "utopic" || $Y_dist = "vivid" || $Y_dist = "wily" || $Y_dist = "xenial" || $Y_dist = "yakkety" || $Y_dist = "zesty" || $Y_dist = "artful" || $Y_dist = "bionic" || $Y_dist = "cosmic" || $Y_dist = "disco" || $Y_dist = "eoan" || $Y_dist = "focal" || $Y_dist = "groovy" || $Y_dist = "hirsute" || $Y_dist = "impish" ]]; then
			sed -i "s/searchdist=.*/searchdist=$Y_dist/g" /tmp/.y-ppa-manager.conf
#			gksu -S -m "Y PPA Manager requires admin privileges for this task" cp /tmp/.y-ppa-manager.conf /etc/y-ppa-manager.conf
#			rm /tmp/.y-ppa-manager.conf
		else
			yad --center --class="y-ppa-manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --form --title="Error" --text="  The Ubuntu version you've entered is not valid  \n  Please enter one of the following versions:  \n impish, hirsute, focal, eoan, bionic or xenial (in lowercase) " --button="gtk-ok:0"
			y_ppa_settings
		fi

	fi

#	if [[ $Y_down != $current_downloads_folder ]]; then
#		escape_Y_down=`echo "$Y_down" | sed -e 's/\//\\\\\//g'`
#		sed -i s/downloads=.*/downloads="$escape_Y_down"/g /tmp/.y-ppa-manager.conf
#	fi

#temporarely_disabled  	if [[ $Y_rank != $current_rankings ]]; then
#temporarely_disabled  		sed -i "s/rankings=.*/rankings=$Y_rank/g" /tmp/.y-ppa-manager.conf
#temporarely_disabled  	fi

initial_settings=$(cat /etc/y-ppa-manager.conf)
new_settings=$(cat /tmp/.y-ppa-manager.conf)

	if [[ $initial_settings != $new_settings ]]; then
		cp /tmp/.y-ppa-manager.conf /etc/y-ppa-manager.conf
		rm /tmp/.y-ppa-manager.conf > /dev/null 2>&1
		su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=dialog-ok \"Y PPA Manager\" \"Settings saved\""
		exit 0
	else
		rm /tmp/.y-ppa-manager.conf > /dev/null 2>&1
		exit 0
	fi


elif [[ $ret -eq 2 ]]; then
	reset_settings

else
	CLEARTEMP
	exit 0

fi

}


help_dialog()
{
	yad --center --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --title="Help - Y PPA Manager" --width="500" --height="400" --text-info  --wrap --filename="/usr/share/y-ppa-manager/y_ppa_man_help" --button="Close:1"

	exit

}

function manage_ppas_notification () 
{
	su $loggeduser -s /bin/bash -c "${DBUS} notify-send -h int:transient:1 -t 10000 -u normal --icon=info \"Y PPA Manager - Working\" \"Getting information about your current PPAs. The Manage PPAs dialog will be displayed shortly.\""
}


#ppa_manager_run()
#{
#MANAGE_PPA=$(yad --center --class="y-ppa-manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --separator=" " --list --width=450 --height=250 --title="Y PPA Manager" --button="Help:3" --button="Exit:1" --button="Select:0" --text="Select an action:" --column=" " --no-headers "Add PPA" "Remove PPA" "Purge PPA" "List packages in a PPA on your computer" "Search packages in all Launchpad PPAs")

#rett=$?

#[[ $rett -eq 1 ]] && rm /tmp/.temp_sourcesnames2.list /tmp/.temp_sources2.list /tmp/.non_disabled2.list /tmp/.temp_sourcesnames.list /tmp/.temp_sources.list /tmp/.non_disabled.list /tmp/+ppas* /tmp/.list_search_results /tmp/.Packages /tmp/.package_search_list_results /tmp/.package_search_list_results2 /tmp/.packagename /tmp/.packageversion /tmp/.packagename2 /tmp/.packageversion2 /tmp/.searched_ppa_names /tmp/.searched_ppas /tmp/.testinternet > /dev/null 2>&1 && exit

#if [[ $rett -eq 3 ]]; then
#help_dialog

#fi

#	case $MANAGE_PPA in
#		Add*)
#		add_a_PPA ;;
#		Remove*)
#		remove_a_PPA ;;
#		Purge*)
#		purge_a_PPA ;;
#		List*)
#		list_packages_PPA ;;
#		Search*)
#		testConnection && exec list_search_ppas ;;
#		*)
#		exit ;;
#	esac
	
#}

#ppa_manager_run


case $1 in
	add)
	add_a_PPA ;;
	advanced)
	advanced_options ;;
	manage)
	manage_ppas_notification && list_packages_PPA ;;
	help)
	help_dialog ;;
	search)
	testConnection && y-ppa-search ;;
	settings)
	y_ppa_settings ;;
	kadd)
	y_add_ppa ;;
	*)
	echo Error, no such option!
	echo
	echo Usage:
	echo y-ppa-cmd add - open the Add PPA dialog
	echo y-ppa-cmd manage - launch the manage PPAs dialog dialog
	echo y-ppa-cmd advanced - launch the advanced options dialog
	echo y-ppa-cmd search - search all Launchpad PPAs dialog
	echo y-ppa-cmd settings - open the settings dialog
	echo y-ppa-cmd help - open the Help dialog
	exit
esac
