#!/bin/bash
#echo "$$" > /tmp/y_pid
Y_RUN_INDICATOR_TRUE=`grep "indicator=enabled" /etc/y-ppa-manager.conf`

function Y_MAIN_DIALOG() {
Y_RUN=$(yad --icons --class="Y-PPA-Manager" --name="Y PPA Manager" --window-icon="/usr/share/icons/hicolor/128x128/apps/y-ppa-manager.png" --item-width="182" --read-dir="/usr/share/y-ppa-manager/desktopfiles" --width="435" --height="440" --title="Y PPA Manager" --auto-kill --text="\n  <b>Double click</b> an item to perform an action:" --button="Settings:2" --button="Help:0" --button="Close:1")
ret=$?
if [[ $ret -eq 0 ]]; then
	Y_MAIN_DIALOG &
	y-ppa-cmd help &
elif [[ $ret -eq 2 ]]; then
	Y_MAIN_DIALOG &
	y-ppa-cmd settings &
else
	if [[ `grep "indicator=enabled" /etc/y-ppa-manager.conf` ]]; then
		killall y-ppa-indicator > /dev/null 2>&1
	fi
	exit 0
fi
}

function Y_RUN() {
if [[ $Y_RUN_INDICATOR_TRUE ]]; then
	Y_MAIN_DIALOG &
	y-ppa-indicator &
else
	Y_MAIN_DIALOG &
fi
}


Y_RUN

