#!/bin/bash
#check if dosudo or kdesudo is installed; run dosudo firstly, if not installed, use kdesudo:
if [[ -e /usr/bin/gksu ]]; then 
	dosudo=gksu
elif [[ -e /usr/bin/kdesudo ]]; then
	dosudo=kdesudo
fi

function add_ppa {
if [[ $dosudo = gksu ]]; then
	gksu -m "Y PPA Manager requires admin privileges for this task" -S "bash -c" "y-ppa-cmd add"
elif [[ $dosudo = kdesudo ]]; then
	kdesudo -d --comment="Y PPA Manager requires admin privileges for this task" "y-ppa-cmd add"
fi
}

function remove_ppa {
if [[ $dosudo = gksu ]]; then
	gksu -m "Y PPA Manager requires admin privileges for this task" -S "bash -c" "y-ppa-cmd remove"
elif [[ $dosudo = kdesudo ]]; then
	kdesudo -d --comment="Y PPA Manager requires admin privileges for this task" "y-ppa-cmd remove"
fi
}


case $1 in
	add)
	add_ppa ;;
	remove)
	remove_ppa ;;
esac
